version: '3.8'

services:
  backgammon-tests:
    build: .
    container_name: backgammon-tests
    volumes:
      - .:/app
    command: sh -c "python3 -m coverage run -m unittest discover tests && python3 -m coverage report -m"

  backgammon-cli:
    build: .
    container_name: backgammon-cli
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: python3 -m cli.cli

  backgammon-pylint:
    build: .
    container_name: backgammon-pylint
    volumes:
      - .:/app
    command: pylint core/ cli/
